# Generated by Django 2.2.5 on 2021-01-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ine',
        ),
    ]
