# Generated by Django 2.2.5 on 2021-01-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ine',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
