# Generated by Django 2.2.5 on 2021-01-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ine_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine',
            name='like',
        ),
    ]
