# Generated by Django 2.2.5 on 2021-01-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210128_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
