# Generated by Django 2.2.5 on 2021-01-30 11:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='To Write with Markdown format', verbose_name='Contents'),
        ),
    ]
